apiVersion: v1
kind: PersistentVolume
metadata:
  name: wso2-mysql-pv-volume
  labels:
    app: wso2-mysql
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.31.31.97
    path: /mnt/LV130GB/wso2/database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wso2-mysql-pv-claim
  labels:
    app: wso2-mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: wso2-mysql-pv-volume
